Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/diamant/Desktop/techstitution/app/mod_main/views.py", line 20, in get_doc
    doc = db.find_one({"_id":ObjectId(id)})
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 121, in __init__
    self.__validate(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 228, in __validate
    _raise_invalid_id(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 61, in _raise_invalid_id
    oid, binary_type.__name__))
InvalidId: u'favicon.ico' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/diamant/Desktop/techstitution/app/mod_main/views.py", line 20, in get_doc
    doc = db.find_one({"_id":ObjectId(id)})
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 121, in __init__
    self.__validate(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 228, in __validate
    _raise_invalid_id(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 61, in _raise_invalid_id
    oid, binary_type.__name__))
InvalidId: u'favicon.ico' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string
Exception on / [POST]
Traceback (most recent call last):
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/diamant/Desktop/techstitution/app/mod_main/views.py", line 20, in get_doc
    doc = db.find_one({"_id":ObjectId(id)})
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 121, in __init__
    self.__validate(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 228, in __validate
    _raise_invalid_id(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 61, in _raise_invalid_id
    oid, binary_type.__name__))
InvalidId: u'favicon.ico' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/diamant/Desktop/techstitution/app/mod_main/views.py", line 20, in get_doc
    doc = db.find_one({"_id":ObjectId(id)})
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 121, in __init__
    self.__validate(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 228, in __validate
    _raise_invalid_id(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 61, in _raise_invalid_id
    oid, binary_type.__name__))
InvalidId: u'favicon.ico' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string
Exception on / [POST]
Traceback (most recent call last):
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/diamant/Desktop/techstitution/app/mod_main/views.py", line 20, in get_doc
    doc = db.find_one({"_id":ObjectId(id)})
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 121, in __init__
    self.__validate(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 228, in __validate
    _raise_invalid_id(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 61, in _raise_invalid_id
    oid, binary_type.__name__))
InvalidId: u'favicon.ico' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/diamant/Desktop/techstitution/app/mod_main/views.py", line 20, in get_doc
    doc = db.find_one({"_id":ObjectId(id)})
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 121, in __init__
    self.__validate(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 228, in __validate
    _raise_invalid_id(oid)
  File "/home/diamant/Desktop/techstitution/venv/local/lib/python2.7/site-packages/bson/objectid.py", line 61, in _raise_invalid_id
    oid, binary_type.__name__))
InvalidId: u'favicon.ico' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string
